- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
      exclude: ^vendor/*
    - id: go-vet
      exclude: ^vendor/*
    - id: go-unit-tests
      exclude: ^vendor/*
    - id: go-build
      exclude: ^vendor/*
